name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Build libshogi
        run: |
          mkdir build && cd build
          cmake -DCODE_COVERAGE=ON ..
          make shogiTests

      - name: Run tests
        run: build/tests/shogiTests

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Create lcov report
        run: |
          cd build
          lcov --capture --directory src --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info 
          lcov --list coverage.info
        
      - name: Upload lcov report to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -f build/coverage.info || echo "Codecov did not collect coverage reports"
